name: Verify

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        width:
          node-version: 12
      - run: npm ci
      - run: npm run lint:js
      - run: npm run lint:css